// src/components/Button.svelte
<style>
  button {
    background: linear-gradient(180deg, #1f0c04 0%, #bd351e 100%);
    border: 1.5px solid #64472c;
    color: #dfb162;
    border-radius: 5px;
    font-size: 14px;
  }
  button:hover:enabled,
  button:active:enabled {
    color: #f6c66a;
  }
</style>

<button {...$$props}>
  <slot />
</button>

// src/components/Button.tsx
import { css } from 'emotion';
import { ButtonHTMLAttributes } from 'react'; // @types/react

const styles = css`
  background: linear-gradient(180deg, #1f0c04 0%, #bd351e 100%);
  border: 1.5px solid #64472C;
  color: #DFB162;
  border-radius: 5px;
  font-size: 14px;
  :hover {
    color: #F6C66A;
  }
`;

const Button = (props: ButtonHTMLAttributes<HTMLButtonElement>) => <button {...props} className={styles} />;

export default Button;
